

export enum ExpenseCategory {
  TRAVEL = 'Travel',
  MEALS = 'Meals',
  LODGING = 'Lodging',
  OFFICE_SUPPLIES = 'Office Supplies',
  SOFTWARE = 'Software',
  ENTERTAINMENT = 'Entertainment',
  OTHER = 'Other',
}

export interface Expense {
  id: string;
  merchant: string;
  amount: number;
  currency: string;
  date: string;
  category: ExpenseCategory | string;
  description: string;
  receiptUrl?: string; // Data URL for display
  status: 'Pending' | 'Approved' | 'Rejected';
  taxDeductibility?: 'Yes' | 'No' | 'Partial';
  taxReasoning?: string;
  submittedBy: string; // Name of the user who submitted this
  companyId: string;
}

export interface Trip {
  id: string;
  destination: string;
  startDate: string;
  endDate: string;
  purpose: string;
  status: 'Planned' | 'Active' | 'Completed';
  budget: number;
  spent: number;
  itinerary?: string; // Markdown itinerary generated by AI
  companyId: string;
}

export interface ReceiptAnalysisResult {
  merchant: string;
  amount: number;
  currency: string;
  date: string;
  category: string;
  description: string;
  confidence: number;
  taxDeductibility?: 'Yes' | 'No' | 'Partial';
  taxReasoning?: string;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
  isError?: boolean;
}

export interface Budget {
  amount: number;
  period: 'Monthly' | 'Yearly';
  lastUpdated: string;
}

export interface EmployeeDocument {
  id: string;
  name: string;
  type: 'PDF' | 'Image' | 'Doc';
  category: 'Contract' | 'ID' | 'Tax' | 'Other';
  uploadDate: string;
  url?: string;
}

export interface Compensation {
  baseSalary: number;
  currency: string;
  effectiveDate: string;
  bonuses?: { date: string; amount: number; reason: string }[];
}

export interface EmploymentDetails {
  jobTitle: string;
  department: string;
  startDate: string;
  managerName?: string;
  managerEmail?: string;
  employmentType: 'Full-time' | 'Part-time' | 'Contract';
  location: string;
}

export interface EmergencyContact {
  name: string;
  relationship: string;
  phone: string;
}

export interface Company {
  id: string;
  name: string;
  domain: string;
  logoUrl?: string;
  subscriptionPlan: string;
  subscriptionStatus: 'Active' | 'Inactive';
  address: string;
  taxId?: string;
  inviteCode: string; // Code for employees to join
}

// -- New Interfaces for Resume/Profile --
export interface ResumeAnalysis {
  matchScore: number;
  matchingSkills: string[];
  missingSkills: string[];
  advice: string;
}

export interface Experience {
  id: string;
  role: string;
  company: string;
  duration: string;
  description: string;
}

export interface Education {
  id: string;
  degree: string;
  institution: string;
  year: string;
}

export interface Achievement {
  id: string;
  title: string;
  description: string;
  date: string;
}

export interface UserProfile {
  name: string;
  email: string;
  role: string;
  phone: string;
  avatarInitials: string;
  avatarUrl?: string;
  companyId?: string; // Link to the company
  budget?: Budget;
  status?: 'Active' | 'Inactive' | 'Pending';
  
  // New Employment Fields
  employment?: EmploymentDetails;
  compensation?: Compensation;
  documents?: EmployeeDocument[];
  emergencyContact?: EmergencyContact;

  // Profile / Applicant Fields
  skills?: string[];
  bio?: string;
  headline?: string;
  experience?: Experience[];
  education?: Education[];
  achievements?: Achievement[];

  // Employer Profile Fields
  company?: string; // Display name
  industry?: string;
  website?: string;
  companySize?: string;
  benefits?: string[];
  location?: string;
}

export type User = UserProfile;

export interface TimeEntry {
  id: string;
  date: string;
  startTime: string;
  endTime: string;
  description: string;
  totalHours: number;
  breakMinutes?: number;
  userId: string;
  userName: string;
  companyId: string;
  status: 'Pending' | 'Approved' | 'Rejected';
}

export enum AbsenceType {
  VACATION = 'Vacation',
  SICK = 'Sick Leave',
  PERSONAL = 'Personal',
  REMOTE = 'Remote Work',
}

export interface AbsenceRequest {
  id: string;
  startDate: string;
  endDate: string;
  type: AbsenceType | string;
  reason: string;
  status: 'Pending' | 'Approved' | 'Rejected';
  userId: string;
  userName: string;
  companyId: string;
}

export interface Job {
  id: string;
  title: string;
  department: string;
  location: string;
  type: 'Full-time' | 'Part-time' | 'Contract' | 'Remote' | 'Internship' | 'Working Student';
  salaryRange: string;
  description: string;
  postedDate: string;
  status: 'Open' | 'Closed';
  companyId: string;
  
  // Expanded fields
  companyName?: string;
  logoUrl?: string;
  requirements?: string[];
  responsibilities?: string[];
  tags?: string[];
}

export type InterviewSentiment = 'Positive' | 'Negative' | 'Neutral';

export interface InterviewFeedback {
  id: string;
  interviewerEmail: string;
  interviewerName: string;
  assignedDate: string;
  completedDate?: string;
  notes?: string;
  sentiment?: InterviewSentiment;
  status: 'Pending' | 'Completed';
}

export interface JobApplication {
  id: string;
  jobId: string;
  applicantName: string;
  applicantEmail: string;
  appliedDate: string;
  status: 'Pending' | 'Interview' | 'Hired' | 'Rejected';
  companyId: string;
  reviews: InterviewFeedback[]; // List of interviews/reviews
  decisionFeedback?: string; // Final feedback sent to applicant
  decisionDate?: string;
  coverNote?: string;
  cvUrl?: string;
  cvName?: string;
}

export interface Praise {
  id: string;
  fromUserName: string;
  fromUserEmail: string;
  fromUserAvatar?: string;
  fromUserInitials: string;
  toUserName: string;
  toUserEmail: string;
  toUserAvatar?: string;
  toUserInitials: string;
  message: string;
  date: string;
  category: 'Teamwork' | 'Innovation' | 'Leadership' | 'Dedication' | 'Helpful';
  companyId: string;
}

export type SurveyQuestionType = 'rating' | 'text';

export interface SurveyQuestion {
  id: string;
  text: string;
  type: SurveyQuestionType;
}

export interface Survey {
  id: string;
  title: string;
  description: string;
  questions: SurveyQuestion[];
  isActive: boolean;
  createdAt: string;
  createdBy: string;
  companyId: string;
}

export interface SurveyResponse {
  id: string;
  surveyId: string;
  userEmail: string;
  answers: { questionId: string; value: string | number }[]; // Value is number for rating, string for text
  submittedAt: string;
  companyId: string;
}

export interface ReviewTemplate {
  id: string;
  name: string;
  role: string; // e.g. "Software Engineer", "Sales", "General"
  questions: string[];
  companyId: string;
}

export interface EmployeeReview {
  id: string;
  period: string; // e.g., "Q4 2023", "2024 Annual"
  employeeName: string;
  employeeEmail: string;
  managerName: string;
  managerEmail: string;
  
  // Unstructured Fallback
  selfReview?: string;
  
  // Structured Questionnaire
  templateId?: string;
  responses?: {
    question: string;
    selfAnswer?: string;
    managerAnswer?: string;
  }[];

  selfRating?: number; // 1-5
  submittedAt?: string;
  
  managerReview?: string; // Overall summary
  managerRating?: number; // 1-5
  completedAt?: string;
  
  status: 'Pending Self' | 'Pending Manager' | 'Completed';
  companyId: string;
}

export interface Goal {
  id: string;
  title: string;
  description: string;
  type: 'Business' | 'Personal';
  visibility: 'Manager' | 'Public';
  status: 'Not Started' | 'In Progress' | 'Completed';
  dueDate: string;
  userId: string;
  userName: string;
  companyId: string;
}

export interface AppNotification {
  id: string;
  title: string;
  message: string;
  date: string;
  type: 'info' | 'success' | 'warning' | 'alert';
  isRead: boolean;
}

export type ViewState = 'dashboard' | 'expenses' | 'trips' | 'settings' | 'team' | 'my-team' | 'time-absence' | 'jobs' | 'recognition' | 'surveys' | 'recruitment' | 'company-settings' | 'notifications' | 'reviews' | 'goals' | 'migo-chat' | 'migo-live' | 'assistant';

// --- Gemini / AI Types ---

export enum Role {
  USER = 'user',
  MODEL = 'model',
}

export interface Attachment {
  mimeType: string;
  data: string; // Base64 encoded data
}

export interface GroundingChunk {
  web?: {
    uri?: string;
    title?: string;
  };
  maps?: {
    uri?: string;
    title?: string;
    placeAnswerSources?: {
      reviewSnippets?: {
         url: string;
      }[]
    }
  };
}

export interface Message {
  id: string;
  role: Role;
  text: string;
  timestamp: number;
  isStreaming?: boolean;
  groundingChunks?: GroundingChunk[];
  isError?: boolean;
}